<?php

/**
 * @file
 * Allows users to login with their username or email address in the same input box.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function login_emailusername_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['name']['#title'] = t('Username or email address.');
  $form['name']['#description'] = t('Enter your username or email address');
  $form['name']['#element_validate'][] = 'login_emailusername_user_login_validate';
}

/**
 * Form element validation handler for the user login form.
 *
 * Allows users to authenticate by username OR email.
 */
function login_emailusername_user_login_validate($form, FormStateInterface $form_state) {
  $name_input = $form_state->getValue('name');

  // Try loading by username.
  if ($user = user_load_by_name($name_input)) {
    return TRUE;
  }

  // Try loading by email.
  if ($user = user_load_by_mail($name_input)) {
    // Set the username for further validation.
    $form_state->setValue('name', $user->getAccountName());
    return TRUE;
  }

  return FALSE;
}
