#!/usr/bin/env bash

# enable pattern lists like +(...|...)
shopt -s extglob

# Note its nice to be able to run the same script locally as well as in CI,
# so we dont rely on circle env vars.
readonly GIT_BRANCH="$(git symbolic-ref --short -q HEAD)"
readonly GIT_REPO="$(basename `git rev-parse --show-toplevel`)"
