abs_urls: false
admin_theme: false
roles_profiles:
  digital_transformation_guide_author:
    public: member
  content_editor:
    public: member
  content_approver:
    public: member
  administrator:
    public: admin
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
