api_key: impy-and-chimpy
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
enable_connected: false
connected_id: null
connected_paths: null
webhook_hash: 7dc01c2b8d09cb9d20716813ebc6212e
